### PR TITLE
fix(logging): fix logging not keeping it's log level in other files

### LINKED ISSUE #104: LOG.info not printing at all? (v1.3.2)
**Describe the bug**
LOG.info calls aren't printing anything to the console
Example `LOG.info(f"====> Epoch: {epoch}, cost {durtaion} s")`

**To Reproduce**
Running `svc train` with the specific model path should do the trick

**Additional context**
I can see LOG.warning calls, especially since I've added those as well, and I couldn't spot anything in regards to the log level being set to only warnings instead of info. I remember seeing info logs in the Google colab I've used though (Might've been with the code from the main repository though)

### PR DESCRIPTION
**Pull request by Lordmau5**
As per suggestion of BlueAmulet, I've created a separate file for logging called `logger.py`.
The other files now import that one instead of creating default logger instances.

This should resolve #104 

It also brings colors back into the terminal
image

### CODE REVIEW

**Comment by BlueAmulet** [comment]
You cannot have getLogger(__name__) called from the logging class cause __name__ be "so_vits_svc_fork.logger" and not the proper place.

Plus you didn't even do anything to resolve the logging to file issue mentioned before.

**Comment by Lordmau5** [comment]
> You cannot have `getLogger(__name__)` called from the logging class cause **name** be "so_vits_svc_fork.logger" and not the proper place.

Well what else would I use instead?

> Plus you didn't even do anything to resolve the logging to file issue mentioned before.

As in, the "multiple processes accessing the same file" issue? Yeah, I wouldn't even know where to start with that.

I've looked around and this so far is the only way I found working (at least in my testing) for it to properly log the `.info` methods, which was what the main issue was about.

How would I go about making it so that the logging instance is only available once globally, or rather, when importing it from the file in other files?

**Comment by BlueAmulet** [comment]
Never mind the file issue, seemed like it wasn't actually a problem.

Modules only import once anyway so that part is taken care of automatically. And instead of calling getLogger in logger.py you have the other files get getLogger from logger.py and call it then:

```
from so_vits_svc_fork.logger import getLogger
LOG = getLogger(__name__)
```

which should already just work since you're importing getLogger in logger.py

**Comment by Lordmau5** [comment]
So instead of
```python
from so_vits_svc_fork.logger import LOG
```

I should instead do this?
```python
from so_vits_svc_fork.logger import getLogger
LOG = getLogger(__name__)
```

**Comment by BlueAmulet** [comment]
Seems like there was some stray log level changes in [src/so_vits_svc_fork/utils.py](https://github.com/34j/so-vits-svc-fork/pull/105/files#diff-8036cfa6b74c166b17d0a5165f2077acbae837bc9b3ceafbe22e191274cd8b62) where warning changed into info

**Comment by Lordmau5** [comment]
> Seems like there was some stray log level changes in [src/so_vits_svc_fork/utils.py](https://github.com/34j/so-vits-svc-fork/pull/105/files#diff-8036cfa6b74c166b17d0a5165f2077acbae837bc9b3ceafbe22e191274cd8b62) where warning changed into info

Intentional. They are supposed to tell the user that something is being removed and it's being cleaned (just like this in train.py - https://github.com/34j/so-vits-svc-fork/blob/main/src/so_vits_svc_fork/train.py#L337 )

**Pull request closed without merging**
