### PR TITLE
fix(notebooks): improves inference

### PR DESCRIPTION
**Pull request by Meldoner**

### CODE REVIEW

**Comment by Meldoner** [comment]
somebody help me with lint issue

**Comment by BlueAmulet** [comment]
It seems to be complaining that the line ending format is changing. The original notebook is in Unix (LF) format but this commit is changing it to Windows (CRLF) format. You may need to play around with git's `core.autocrlf` config setting.

**Comment by Meldoner** [comment]
> It seems to be complaining that the line ending format is changing. The original notebook is in Unix (LF) format but this commit is changing it to Windows (CRLF) format. You may need to play around with git's `core.autocrlf` config setting, or use the dos2unix command.

THANK U

**Comment by Meldoner** [comment]
@34j I fixed all errors

**Pull request merged**
